### ISSUE TITLE
Access REMOTE_USER

### ISSUE THREAD

**Issue by userg3003** [abersheeran/a2wsgi#10]
The CGI RFC provides for a REMOTE_USER variable, which holds the username of the user who has been authenticated by the front-end Web server. For a WSGI application, this can be obtained as environ["REMOTE_USER"], since a WSGI application gets access to all CGI variables. It would be nice if an ASGI application could get access to the same thing.
For example, if I run the Flask application under the Apache server, with authorization through Active Directory, I can get the name of the authorized user in the remote_user variable.
Note: missing variables (such as REMOTE_USER when no authentication has occurred) should be left out of the environ dictionary (
[PEP 3333](https://www.python.org/dev/peps/pep-3333/#environ-variables)).

To add the ability to access REMOTE_USER , you can do the following in asgi.py (in def build_scope(environ: Environ) -> Scope:):
```python
def build_scope(environ: Environ) -> Scope:

    ...

    if environ.get("REMOTE_USER"):
        remote_user = environ.get("REMOTE_USER")
    else:
        remote_user = None


    return {
        "type": "http",
        "asgi": {"version": "3.0", "spec_version": "3.0"},
        "http_version": environ.get("SERVER_PROTOCOL", "http/1.0").split("/")[1],
        "method": environ["REQUEST_METHOD"],
        "scheme": environ.get("wsgi.url_scheme", "http"),
        "path": environ["PATH_INFO"].encode("latin1").decode("utf8"),
        "query_string": environ["QUERY_STRING"].encode("ascii"),
        "root_path": environ.get("SCRIPT_NAME", "").encode("latin1").decode("utf8"),
        "client": client,
        "server": (environ["SERVER_NAME"], int(environ["SERVER_PORT"])),
        "headers": headers,
        "remote_user": remote_user,
    }
```

**Comment by abersheeran** [comment]
Great idea, but it is not part of the ASGI standard. You should go to [asgiref](https://github.com/django/asgiref) to create a PR. When it becomes a standard, a2wsgi will quickly follow up on this part.
