### ISSUE TITLE
Converting FastAPI  app to WSGI and use it on cPanel

### ISSUE THREAD

**Issue by keyvan-najafy** [abersheeran/a2wsgi#16]
Hi
I have a very simple FastAPI app which I need to run on a host with cPanel
when I convert my app using a2wsgi and test it on local host using Werkzeug package (which only supports WSGI therefor cant run FastAPI app without conversion ) it works fine but when I deploy it on cPanel server takes too long to process and the returns this

![image](https://user-images.githubusercontent.com/57255601/129590400-6199a775-49de-44ff-92fb-2934d0e99400.png)

I also tried to avoid cPanel regular UI for creating python apps and used terminal to deploy instead but the result is the same
Can anyone help me with this ?

**Comment by abersheeran** [comment]
I'm not familiar with cPanel. But the following code maybe have help for you to debuging:

```python
app = your_app

async def log_middleware(scope, receive, send):
    async def _receive():
        msg = await receive()
        print(msg)
        return msg

    async def _send(msg):
        print(msg)
        await send(msg)

     return await app(scope, _receive, _send)
```

Read the output, you can know where the code is hanging.

**Comment by keyvan-najafy** [comment]
This is the only output even with an additional logger and middleware:
`
2021-08-17 17:22:13.478701 [UID:1361][1070483] Child process with pid: 1070487 was killed by signal: 15, core dump: 0
`
but the code stays same like before.

**Comment by abersheeran** [comment]
It's look like your fastapi process be kiiled.

**Comment by christophe-deleuze** [comment]
Hello,

On my side everything is fine with cpanel and fastapi.

Firstly check that your passenger_wsgi.py looks like that :

from a2wsgi import ASGIMiddleware
from api import app  # Import your FastAPI app.

application = ASGIMiddleware(app)

Then, check that the API domain shouldn't be the same as another existing
domain.
I recommend to set a subdomaine like :

main domain : mydomain.com
api subdomain : api.mydomain.com

Generally, this 2 thinks are enought to solve the issue.

**Comment by keyvan-najafy** [comment]
Sadly I switched to a cloud service with docker so I cant comment on this anymore but I used the same method on passenger_wsgi.py.
As for API domain I did not used what you said so maybe that was the problem.
Also my cPanel version was a bit old so it would be great if you share your cPanel version.

**Comment by mdkberry** [comment]
This was closed but is the only place I found help to start to get through this same problem so will share here for others running into it. 
I was getting the exact same error message in my _stderr.log_ in the python app folder regards child processes until I changed the code in passenger_wsgi.py to _from main import app_ but then  I started getting 503 errors and found a lot of others had too with django attempts (I am using FastAPI). Nothing shows in the CPanel metrics errors other than "file missing" and no more errors were being added to the _stderr.log_ which was weird... first thing I tried was stopping and starting the python app but still nothing.

so do this... run the python code from the terminal in CPanel using the source code it gives you in python app setup config at the top using  "python passenger_wsgi.py"

one problem is the indentation in the debug code snippet shared by abersheeran. the code wont run and needs the white space removed from  _" return await app(scope, _receive, _send)"_
now my code runs the wrong thing, but it runs from a browser. I have now run into other issues but will share the solution if I find them. I believe the initial problem to this working might have been that white space issue.

**Comment by mdkberry** [comment]
didnt solve it. I also set it up on it's own subdomain as per christophe-deleuze suggestion and when I add the fast-api main.py back in it fails to work and I get the dreaded _[UID:1293][19858] Child process with pid: 20085 was killed by signal: 15, core dump: 0_ error which seems to be common for everyone and have no solutions suggested anywhere at this time.

**Comment by abersheeran** [comment]
All seem to be caused by the process being killed.

**Comment by mdkberry** [comment]
for some, and not others. shame no one has found a cause or solution. I have given it one last shot by posting the issue on stackoverflow. after that I am going to have to look at server hosting it.
