### ISSUE TITLE
'NoneType' object has no attribute 'read'

### ISSUE THREAD

**Issue by krieu** [abersheeran/a2wsgi#26]
Hi, I'm deploying an app made with fastapi to AWS Lambda with zappa.
The POST request works fine, but I get an error with the GET request.

```
data = body.read(min(4096, content_length - read_count))\\n', \"AttributeError: 'NoneType' object has no attribute 'read'
```

If wsgi.input was None, assigning an empty stream will work.
```
class ASGIMiddlewareWrapper(ASGIMiddleware):
    def __call__(
        self, environ: Environ, start_response: StartResponse
    ) -> Iterable[bytes]:
        if not environ["wsgi.input"]:
            environ["wsgi.input"] = io.StringIO()
        return ASGIResponder(self.loop, self.app, wait_time=self.wait_time)(
            environ, start_response
        )
```

**Comment by abersheeran** [comment]
After I re-read the part about wsgi.input in PEP3333, I found that the spec doesn't say whether it is required or not.

I'm a little hesitant about what to do with a2wsgi here, maybe reading how projects like django, flask, waitress, etc. handle it would help, but I don't have the time right now.

Thanks for the code you shared, it's a working fix.

**Comment by abersheeran** [comment]
I looked at the relevant code for some of the frameworks and it doesn't seem like they handle this situation. I'm guessing this is because `fastapi` tries to read `request.body` anyway.
