### ISSUE TITLE
Gateway timeout with ASGIMiddleware and uwsgi

### ISSUE THREAD

**Issue by ldperron** [abersheeran/a2wsgi#34]
I have a server running uwsgi in emperor mode, but I also want to run FastAPI/ASGI apps under the uwsgi emperor.
Unfortunately, with ASGIMiddleware, I'm able to load a vassal without errors in the logs, but unfortunately, all requests leads to a gateway timeout error. When I strace the vassal worker, it's indefinitely stuck on a futex() system call.
Anyone has to debug this further? Or what I'm trying to do is actually impossible?

Thanks

**Comment by abersheeran** [comment]
It would be helpful if you could give the configuration of uwsgi you are using.

**Comment by ldperron** [comment]
No problem! Here they are:

emperor.ini:
```
[uwsgi]
uid = uwsgi
gid = uwsgi
emperor = /misc/apps/uwsgi/*.ini
chmod-socket = 660
emperor-tyrant = true
emperor-tyrant-nofollow = true

cap = setgid,setuid

vassal-set = vacuum=true
vassal-set = enable-threads=true
vassal-set = die-on-term=true
vassal-set = reload-on-rss=500
vassal-set = max-requests=500
vassal-set = harakiri=600
```

vassal.ini:
```
[uwsgi]
chdir = /misc/apps/ldp
plugins = python310,logfile  
enable-threads = true
module = fa:app
processes = 1
chmod-socket = 666
virtualenv = /misc/venvs/py310/
socket = /uwsgi-sockets/%n.sock
```

Finally fa.py:
```
from fastapi import FastAPI
from a2wsgi import ASGIMiddleware

app = FastAPI()

@app.get("/")
async def root():
    return {"message": "Hello World"}
    
app = ASGIMiddleware(app)
```

**Comment by abersheeran** [comment]
Are there any started logs？

**Comment by ldperron** [comment]
Good news! While trying to get better logs, I found out that adding `lazy = true` in my ini fixes the problem!

**Comment by abersheeran** [comment]
Good job! 😁
