### ISSUE TITLE
Headers containing underscores should be ignored?

### ISSUE THREAD

**Issue by nmoreaud** [abersheeran/a2wsgi#62]
Hello
I am using Connexion framework to deliver a Rest API.
My production server (nginx + gunicorn + flask) dropped every header containing an underscore "_".
Please note that this is done by default by nginx and apache.
https://stackoverflow.com/questions/22856136/why-do-http-servers-forbid-underscores-in-http-header-names
https://stackoverflow.com/questions/43011065/apache-convert-underscores-to-dashes-in-headers
https://github.com/pallets/werkzeug/commit/5ee439a692dc4474e0311de2496b567eed2d02cf#diff-abeaeb33abe8954dc4551a4631392ac46ad65e8b9f8404cec0e276a0d345af3bL204
https://github.com/pallets/werkzeug/issues/2693

My development server didn't do it (old version of werkzeug) and my team had a hard time when it discovered that there were typographies in our code (ex: `headers['MY_CUSTOM_HEADER'] = 'minimal'`), visible only on the production environment.
This was fixed by werkzeug 2.3.3.

However with Connexion v3, I now use a2wsgi which normalizes my headers (ex MY_CUSTOM_HEADER => MY-CUSTOM-HEADER), and again it is risky because it might hide bugs in our codebase.

What do you think about dropping headers with underscores?
[a2wsgi/wsgi.py:139](https://github.com/abersheeran/a2wsgi/blob/d19c7079734be7222b00c8b784ea5560f89731e5/a2wsgi/wsgi.py#L139)

**Comment by abersheeran** [comment]
https://stackoverflow.com/a/22857932/9301113 Here, I prefer to adhere to the RFC standard and not make any additional processing for headers (i.e., not deleting header entries containing underscores). If you have such a requirement, you can write a pure ASGI middleware to wrap it around a2wsgi.WSGIMiddleware.

**Comment by nmoreaud** [comment]
@abersheeran Ok I understand that, but currently underscores are replaced with dashes. I don't know the RFC well, but  isn't this additional processing?

**Comment by nmoreaud** [comment]
Ok, so you are right, it is easy to handle with a middleware: 

```python
class MyMiddleware:
    def __init__(self, app: ASGIApp):
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope['type'] in ('http', 'websocket'):
            scope['headers'] = [h for h in scope['headers'] if '_' not in h[0].decode()]
        return await self.app(scope, receive, send)
```

**Comment by abersheeran** [comment]
Haha, great share.
